name: Build App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
env:
  AZURE_WEBAPP_NAME: 'app-soat-bc22-dev-fr-01'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Build
      run: dotnet build --configuration Release

    - name: Generate Database Initialisation Script
      run: |
        dotnet tool install --global dotnet-ef
        dotnet ef migrations script --idempotent --startup-project Soat.AntiGaspi.Api --output postgres/00_init.sql
    
    - name: Cache docker layer
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Run Docker Compose
      run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d

    - name: Wait for database to be up...
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- localhost:5432 -- echo "Database is up"
      env:
        WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release --no-build -o ./out    
    
    - name: Archive SQL scripts artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sql-artifact
        path: src/postgres

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: src/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    defaults:
      run:
        working-directory: ./deploy

    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Apply
      id: terraform-apply
      run: terraform apply -auto-approve
        
    - name: Terraform Outputs
      id: terraform-outputs
      run: |
        # Export Terraform output as step outputs
        $terraformOutput = (terraform output -json | ConvertFrom-Json -AsHashtable)     
        foreach ($key in $terraformOutput.Keys) {
          $outputVariableValue = $terraformOutput[$key].value
          Write-Output "::set-output name=${key}::${outputVariableValue}"
        } 
      shell: pwsh

    - name: Download SQL artifacts
      uses: actions/download-artifact@v3
      with:
        name: sql-artifact

    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    - name: Update Azure database
      uses: azure/postgresql@v1
      with:
        server-name: ${{ steps.terraform-outputs.outputs.postgresql_name }}
        connection-string: "psql host=${{ steps.terraform-outputs.outputs.postgresql_url }} port=5432 user=${{ steps.terraform-outputs.outputs.postgresql_user }} password=${{ steps.terraform-outputs.outputs.postgresql_password }} dbname=${{ steps.terraform-outputs.outputs.postgresql_database_name }} sslmode=require"
        plsql-file: './00_init.sql'

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact

    - name: Deploy to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'