name: Build App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
 run:
  working-directory: ./src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run PostgreSQL
      run: |
        cd ..
        docker compose up -d
    - name: Run Database Migration
      run: |
        dotnet tool install --global dotnet-ef
        dotnet ef database update
    - name: Test
      run: dotnet test --no-build --verbosity normal
