name: Build App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Build
      run: dotnet build --configuration Release

    - name: Generate Database Initialisation Script
      run: |
        dotnet tool install --global dotnet-ef
        dotnet ef migrations script --configuration Release --no-build --idempotent --startup-project Soat.AntiGaspi.Api --output postgres/00_init.sql
    
    - name: Archive SQL scripts artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sql-artifact
        path: src/postgres
    
    - name: Publish
      run: dotnet publish -c Release --no-build -o ./out    
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: src/out