name: Build App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
env:
  AZURE_WEBAPP_NAME: 'app-soat-bc22-dev-fr-01'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Build
      run: dotnet build --configuration Release

    - name: Generate Database Initialisation Script
      run: |
        cd Soat.AntiGaspi.Api
        dotnet tool install --global dotnet-ef
        dotnet ef dbcontext script --configuration Release --no-build --output ../postgres/00_init.sql

    - name: Cache docker layer
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Run Docker Compose
      run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d

    - name: Wait for database to be up...
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- localhost:5432 -- echo "Database is up"
      env:
        WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release --no-build -o ./out
      
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: src/out

    - name: Archive SQL scripts artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sql-artifact
        path: src/postgres

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    defaults:
      run:
        working-directory: ./deploy

    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Apply
      id: terraform-apply
      run: terraform apply -input=false -auto-approve

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact

    - name: Update Azure database      
      run: |        
        dotnet tool install --global dotnet-ef
        dotnet ef database update --connection ${{ steps.terraform-apply.outputs.potgresql_connection_string }}

    - name: Deploy to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'